[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log

[program:python_daemon]
command=python3 /app/lab_daemon.py
autostart=true
autorestart=true
stdout_logfile=/var/log/python_daemon.out.log
stderr_logfile=/var/log/python_daemon.err.log


[program:prometheus]
command=/usr/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus
autostart=true
autorestart=true

[program:grafana]
# Removed 'user=grafana' to let Docker's root handle the initial execution
# Added explicit paths to avoid 'exit status 1'
command=/usr/sbin/grafana-server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini --packaging=docker cfg:default.paths.logs=/var/log/grafana cfg:default.paths.data=/var/lib/grafana
autostart=true
autorestart=true
stdout_logfile=/var/log/grafana.out.log
stderr_logfile=/var/log/grafana.err.log
